basePath: /
definitions:
  types.AuthRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  types.FilterParametesRequest:
    properties:
      name:
        type: string
      parameters:
        $ref: '#/definitions/types.ParametesRequest'
    type: object
  types.FilterRequest:
    properties:
      filter:
        $ref: '#/definitions/types.FilterParametesRequest'
    type: object
  types.HandlerResponse:
    properties:
      value:
        type: string
    type: object
  types.ParametesRequest:
    properties:
      value: {}
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: My API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user and return a session token.
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.HandlerResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Login User
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with a username and password.
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.HandlerResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Register User
      tags:
      - Auth
  /task:
    post:
      consumes:
      - application/json
      description: Create a new task with specified filters and parameters.
      parameters:
      - description: Filter details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/types.FilterRequest'
      - description: Authorization token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.HandlerResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Task with Filters
      tags:
      - Task
  /task/result/{taskID}:
    get:
      description: Retrieve the result of a task by its ID.
      parameters:
      - description: Task ID
        in: path
        name: taskID
        required: true
        type: string
      - description: Authorization token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.HandlerResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get Task Result
      tags:
      - Task
  /task/status/{taskID}:
    get:
      description: Retrieve the status of a task by its ID.
      parameters:
      - description: Task ID
        in: path
        name: taskID
        required: true
        type: string
      - description: Authorization token in the format 'Bearer <token>'
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.HandlerResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get Task Status
      tags:
      - Task
swagger: "2.0"
